language: node_js
sudo: false
node_js:
  - "6"
before_script:
  - npm install -g bower
  - bower install
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install
script:
 - npm test
after_script:
 - cat ./coverage/report-lcov/lcov.info | ./node_modules/coveralls/bin/coveralls.js
notifications:
  slack: $NOTIFICATIONS_SLACK